#!/usr/bin/env bash
set -euo pipefail

# Simple tag replacement script for this repo
# Scans a set of files and replaces placeholder tags with user-provided values.

FILES=(composer.json functions.php LICENSE style.css theme.json)

TAGS=(
  "%text-domain%"
  "%pretty-name%"
  "%description%"
  "%author-name%"
  "%author-email%"
  "%author-homepage%"
  # "%function-name%" is generated from %text-domain%
  # "%class-name%" is generated from %text-domain%
)

echo "Scanning files: ${FILES[*]}"

# Auto-generate and replace %year% with the current year
year=$(date +%Y)
echo "Auto-replacing %year% -> ${year}"
for f in "${FILES[@]}"; do
  if [ -f "$f" ]; then
    REPL="$year" perl -0777 -i -pe 's/\Q%year%\E/$ENV{REPL}/g' "$f"
  fi
done

for tag in "${TAGS[@]}"; do
  if [ "${tag}" = "%text-domain%" ]; then
    # text-domain is required; keep prompting until provided
    value=""
    while [ -z "$value" ]; do
      read -rp "Replacement for ${tag} (required): " value
      if [ -z "$value" ]; then
        echo "Value required for ${tag}."
      fi
    done

    text_domain="$value"

    # generate function-name: replace non-alnum with underscore, collapse underscores
    function_name=$(echo "$value" | sed 's/[^a-zA-Z0-9]/_/g' | sed 's/_\+/_/g' | sed 's/^_//; s/_$//')

    # generate class-name: treat %text-domain% as kebab-case (words separated by '-')
    # normalize: lowercase and replace non-alnum with '-' so separators are consistent
    normalized=$(echo "$value" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g')
    IFS='-' read -r -a parts <<< "$normalized"
    class_name=""
    for part in "${parts[@]}"; do
      if [ -n "$part" ]; then
        class_name+="${part^}_"
      fi
    done
    class_name="${class_name%_}"  # remove trailing underscore

    # perform replacements for text-domain, function-name, and class-name
    for f in "${FILES[@]}"; do
      if [ -f "$f" ]; then
        REPL="$value" perl -0777 -i -pe 's/\Q%text-domain%\E/$ENV{REPL}/g' "$f"
        REPL="$function_name" perl -0777 -i -pe 's/\Q%function-name%\E/$ENV{REPL}/g' "$f"
        REPL="$class_name" perl -0777 -i -pe 's/\Q%class-name%\E/$ENV{REPL}/g' "$f"
      else
        echo "Warning: $f not found, skipping." >&2
      fi
    done
    continue
  fi

  # For all other tags: require non-empty input
  value=""
  while [ -z "$value" ]; do
    read -rp "Replacement for ${tag} (required): " value
    if [ -z "$value" ]; then
      echo "Value required for ${tag}."
    fi
  done

  # Store some tag values for later use (README overwrite)
  if [ "${tag}" = "%pretty-name%" ]; then
    pretty_name="$value"
  elif [ "${tag}" = "%description%" ]; then
    description="$value"
  fi

  for f in "${FILES[@]}"; do
    if [ -f "$f" ]; then
      REPL="$value" perl -0777 -i -pe 's/\Q'"${tag}"'\E/$ENV{REPL}/g' "$f"
    else
      echo "Warning: $f not found, skipping." >&2
    fi
  done
done

# If pretty-name and description were provided, overwrite README.md
if [ -n "${pretty_name:-}" ] &&
  [ -n "${description:-}" ] &&
  [ -n "${text_domain:-}" ] &&
  [ -n "${function_name:-}" ] &&
  [ -n "${class_name:-}" ]; then

  echo "Overwriting README.md with provided information."

cat << EOF | tee README.md > /dev/null
# $pretty_name

$description

This is a child theme of Twenty Twenty-Five generated by the \`replace-tags.sh\` script.

## Development

The text domain of this theme is set to \`$text_domain\`. All functions should
be prefixed with \`$function_name\` and all classes should use the WordPress
standard class name format \`$class_name\`.

To run code quality checks on this theme, use the following command:

\`\`\`bash
composer lint
\`\`\`

To run static analysis on this theme, use the following command:

\`\`\`bash
composer phpstan
\`\`\`
EOF

fi

echo "Done."
